name: Deploy to Firebase Hosting on dispash to Prod
on: workflow_dispatch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY_PROD }}
      REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN_PROD }}
      REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID_PROD }}
      REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET_PROD }}
      REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID_PROD }}
      REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID_PROD }}
      REACT_APP_SLACK_TOKEN: ${{ secrets.REACT_APP_SLACK_TOKEN_PROD }}
      CI: false
      REACT_APP_PROD: "production"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BABYFOOT_APP_PROD }}"
          channelId: live
          projectId: babyfoot-app-prod
